services:
  gepetto_devcontainer:
    build: .
    ipc: host
    network_mode: host
    privileged: true
    tty: true
    volumes:
      - ../:/home/gepetto/ros2_ws/src:cached
      - .:/home/gepetto/ros2_ws:cached
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev:/dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
    command: sleep infinity
